export default {
	"EN" : {
		"title" : "THIS IS AN ENGLISH TITLE ",
		"general.open" : "OPEN",
		"general.close" : "CLOSE",
		"general.cancel" : "CANCEL",
		"general.startmeeting" : "START MEETING",
		"general.stopmeeting" : "STOP MEETING",
		"general.reserved" : "RESERVED",
		"general.free" : "FREE",
		"general.occupied" : "OCCUPIED",
		"notconnected.title" : "NOT CONNECTED",
		"notconnected.subtitle" : "But don't worry! We're automatically trying to restore the connection",
		"free.title" : "FREE",
		"usemeetingroom.button" : "USE MEETING ROOM",
		"freemeetingrooms.title" : "Free meeting rooms",
		"freemeetingrooms.persons" : "Persons",
		"freemeetingrooms.until" : "until",
		"freemeetingrooms.error" : "We're sorry. There are no free rooms.",
		"newreservation.title" : "Reserve",
		"newreservation.length" : "How long is this meeting going to be?",
		"newreservation.who" : "Who are you?",
		"newreservation.error.time" : "Unfortunately it is not possible to make a new reservation. Another reservation will start within 15 minutes.",
		"newreservation.error.name" : "We're sorry, but you need to select a name from the drop down menu.",
		"date.day.monday" : "Monday",
		"date.day.tuesday" : "Tuesday",
		"date.day.wednesday" : "Wednesday",
		"date.day.thursday" : "Thursday",
		"date.day.friday" : "Friday",
		"date.day.saturday" : "Saturday",
		"date.day.sunday" : "Sunday",
		"date.month.january" : "January",
		"date.month.february" : "February",
		"date.month.march" : "March",
		"date.month.april" : "April",
		"date.month.may" : "May",
		"date.month.june" : "June",
		"date.month.july" : "July",
		"date.month.august" : "August",
		"date.month.september" : "September",
		"date.month.october" : "October",
		"date.month.november" : "November",
		"date.month.december" : "December",
	},
	"NL" : {
		"title" : "DIT IS EEN NEDERLANDSE TITEL",
		"general.open" : "OPEN",
		"general.close" : "SLUIT",
		"general.cancel" : "ANNULEER",
		"general.startmeeting" : "START VERGADERING",
		"general.stopmeeting" : "STOP VERGADERING",
		"general.reserved" : "GERESERVEERD",
		"general.free" : "VRIJ",
		"general.occupied" : "BEZET",
		"notconnected.title" : "NIET VERBONDEN",
		"notconnected.subtitle" : "Geen zorgen! We proberen automatisch de verbinding te herstellen",
		"free.title" : "VRIJ",
		"usemeetingroom.button" : "GEBRUIK VERGADERRUIMTE",
		"freemeetingrooms.title" : "Vrije vergaderruimten",
		"freemeetingrooms.persons" : "Personen",
		"freemeetingrooms.until" : "tot",
		"freemeetingrooms.error" : "Helaas, er zijn geen vrije vergaderruimten.",
		"newreservation.title" : "Reserveren",
		"newreservation.length" : "Hoe lang zal deze vergadering gaan duren?",
		"newreservation.who" : "Wie ben jij?",
		"newreservation.error.time" : "Helaas is het niet mogelijk om de nieuwe reservering in te plannen. Een volgende reservering begint namelijk binnen 15 minuten.",
		"newreservation.error.name" : "Selecteer alstublieft eerst een naam uit de keuzelijst.",
		"date.day.monday" : "Maandag",
		"date.day.tuesday" : "Dinsdag",
		"date.day.wednesday" : "Woensdag",
		"date.day.thursday" : "Donderdag",
		"date.day.friday" : "Vrijdag",
		"date.day.saturday" : "Zaterdag",
		"date.day.sunday" : "Zondag",
		"date.month.january" : "Januari",
		"date.month.february" : "Februari",
		"date.month.march" : "Maart",
		"date.month.april" : "April",
		"date.month.may" : "Mei",
		"date.month.june" : "Juni",
		"date.month.july" : "Juli",
		"date.month.august" : "Augustus",
		"date.month.september" : "September",
		"date.month.october" : "October",
		"date.month.november" : "November",
		"date.month.december" : "December",
	}
}
